version: "2.0"
services:
  grafana:
    build: ./grafana
    ports: 
      - "80:80"
    volumes:
        - grafana_etc:/etc/grafana
        - grafana_usr:/usr/share/grafana 
        - grafana_var:/var/lib/grafana
    container_name: grafana

volumes:
    grafana_etc:
    grafana_usr:
    grafana_var: